services:
  php-fpm:
    #image: php:8.4-fpm
    image: my-ecs-php-fpm
    networks:
      - app-network
    environment:
      APP_KEY: base64:slBwwE6jbHjJSLHAlWbVvm9WUeqJrAQO/QaMrbdfcuA=

  nginx:
    #image: nginx:alpine
    image: my-ecs-nginx
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - app-network

networks:
  app-network:
